### ISSUE TITLE
[Errno 2] No such file or directory: '/public1/work/jinwen/software/MM-ncRNAFP/main/transformers-cli'

### ISSUE THREAD

**Issue by JinwnK** [xuruiting2/MM-ncRNAFP#1]
When I run `pip install -e . `， I encounter the following error. Could you please help me resolve this issue?

`pip install -e .
Obtaining file:///public1/work/jinwen/software/MM-ncRNAFP/main
  Preparing metadata (setup.py) ... done
Requirement already satisfied: numpy in /public1/work/jinwen/software/miniconda3/envs/mmncrnafp/lib/python3.8/site-packages (from transformers==2.5.0) (1.24.4)
Requirement already satisfied: tokenizers==0.5.0 in /public1/work/jinwen/software/miniconda3/envs/mmncrnafp/lib/python3.8/site-packages (from transformers==2.5.0) (0.5.0)
Requirement already satisfied: boto3 in /public1/work/jinwen/software/miniconda3/envs/mmncrnafp/lib/python3.8/site-packages (from transformers==2.5.0) (1.23.10)
Requirement already satisfied: filelock in /public1/work/jinwen/software/miniconda3/envs/mmncrnafp/lib/python3.8/site-packages (from transformers==2.5.0) (3.4.1)
Requirement already satisfied: requests in /public1/work/jinwen/software/miniconda3/envs/mmncrnafp/lib/python3.8/site-packages (from transformers==2.5.0) (2.31.0)
Requirement already satisfied: tqdm>=4.27 in /public1/work/jinwen/software/miniconda3/envs/mmncrnafp/lib/python3.8/site-packages (from transformers==2.5.0) (4.66.1)
Requirement already satisfied: regex!=2019.12.17 in /public1/work/jinwen/software/miniconda3/envs/mmncrnafp/lib/python3.8/site-packages (from transformers==2.5.0) (2023.8.8)
Requirement already satisfied: sentencepiece in /public1/work/jinwen/software/miniconda3/envs/mmncrnafp/lib/python3.8/site-packages (from transformers==2.5.0) (0.1.91)
Requirement already satisfied: sacremoses in /public1/work/jinwen/software/miniconda3/envs/mmncrnafp/lib/python3.8/site-packages (from transformers==2.5.0) (0.0.53)
Requirement already satisfied: botocore<1.27.0,>=1.26.10 in /public1/work/jinwen/software/miniconda3/envs/mmncrnafp/lib/python3.8/site-packages (from boto3->transformers==2.5.0) (1.26.10)
Requirement already satisfied: jmespath<2.0.0,>=0.7.1 in /public1/work/jinwen/software/miniconda3/envs/mmncrnafp/lib/python3.8/site-packages (from boto3->transformers==2.5.0) (1.0.1)
Requirement already satisfied: s3transfer<0.6.0,>=0.5.0 in /public1/work/jinwen/software/miniconda3/envs/mmncrnafp/lib/python3.8/site-packages (from boto3->transformers==2.5.0) (0.5.2)
Requirement already satisfied: charset-normalizer<4,>=2 in /public1/work/jinwen/software/miniconda3/envs/mmncrnafp/lib/python3.8/site-packages (from requests->transformers==2.5.0) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in /public1/work/jinwen/software/miniconda3/envs/mmncrnafp/lib/python3.8/site-packages (from requests->transformers==2.5.0) (3.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in /public1/work/jinwen/software/miniconda3/envs/mmncrnafp/lib/python3.8/site-packages (from requests->transformers==2.5.0) (1.26.18)
Requirement already satisfied: certifi>=2017.4.17 in /public1/work/jinwen/software/miniconda3/envs/mmncrnafp/lib/python3.8/site-packages (from requests->transformers==2.5.0) (2023.7.22)
Requirement already satisfied: six in /public1/work/jinwen/software/miniconda3/envs/mmncrnafp/lib/python3.8/site-packages (from sacremoses->transformers==2.5.0) (1.16.0)
Requirement already satisfied: click in /public1/work/jinwen/software/miniconda3/envs/mmncrnafp/lib/python3.8/site-packages (from sacremoses->transformers==2.5.0) (8.0.4)
Requirement already satisfied: joblib in /public1/work/jinwen/software/miniconda3/envs/mmncrnafp/lib/python3.8/site-packages (from sacremoses->transformers==2.5.0) (1.3.2)
Requirement already satisfied: python-dateutil<3.0.0,>=2.1 in /public1/work/jinwen/software/miniconda3/envs/mmncrnafp/lib/python3.8/site-packages (from botocore<1.27.0,>=1.26.10->boto3->transformers==2.5.0) (2.8.2)
Installing collected packages: transformers
  Running setup.py develop for transformers
    error: subprocess-exited-with-error
    
    × python setup.py develop did not run successfully.
    │ exit code: 1
    ╰─> [16 lines of output]
        running develop
        running egg_info
        writing src/transformers.egg-info/PKG-INFO
        writing dependency_links to src/transformers.egg-info/dependency_links.txt
        writing requirements to src/transformers.egg-info/requires.txt
        writing top-level names to src/transformers.egg-info/top_level.txt
        reading manifest file 'src/transformers.egg-info/SOURCES.txt'
        writing manifest file 'src/transformers.egg-info/SOURCES.txt'
        running build_ext
        Creating /public1/work/jinwen/software/miniconda3/envs/mmncrnafp/lib/python3.8/site-packages/transformers.egg-link (link to src)
        Adding transformers 2.5.0 to easy-install.pth file
        /public1/work/jinwen/software/miniconda3/envs/mmncrnafp/lib/python3.8/site-packages/setuptools/command/easy_install.py:156: EasyInstallDeprecationWarning: easy_install command is deprecated. Use build and pip and other standards-based tools.
          warnings.warn(
        /public1/work/jinwen/software/miniconda3/envs/mmncrnafp/lib/python3.8/site-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
          warnings.warn(
        error: [Errno 2] No such file or directory: '/public1/work/jinwen/software/MM-ncRNAFP/main/transformers-cli'
        [end of output]
    
    note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× python setup.py develop did not run successfully.
│ exit code: 1
╰─> [16 lines of output]
    running develop
    running egg_info
    writing src/transformers.egg-info/PKG-INFO
    writing dependency_links to src/transformers.egg-info/dependency_links.txt
    writing requirements to src/transformers.egg-info/requires.txt
    writing top-level names to src/transformers.egg-info/top_level.txt
    reading manifest file 'src/transformers.egg-info/SOURCES.txt'
    writing manifest file 'src/transformers.egg-info/SOURCES.txt'
    running build_ext
    Creating /public1/work/jinwen/software/miniconda3/envs/mmncrnafp/lib/python3.8/site-packages/transformers.egg-link (link to src)
    Adding transformers 2.5.0 to easy-install.pth file
    /public1/work/jinwen/software/miniconda3/envs/mmncrnafp/lib/python3.8/site-packages/setuptools/command/easy_install.py:156: EasyInstallDeprecationWarning: easy_install command is deprecated. Use build and pip and other standards-based tools.
      warnings.warn(
    /public1/work/jinwen/software/miniconda3/envs/mmncrnafp/lib/python3.8/site-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
      warnings.warn(
    error: [Errno 2] No such file or directory: '/public1/work/jinwen/software/MM-ncRNAFP/main/transformers-cli'
    [end of output]

note: This error originates from a subprocess, and is likely not a problem with pip.`

**Comment by lucianozablocki** [comment]
hmm i could install it successfully (i only had to modify a path in `main/setup.py`). did you try this in an isolated virtual env?

**Comment by JinwnK** [comment]
> hmm i could install it successfully (i only had to modify a path in `main/setup.py`). did you try this in an isolated virtual env?

Thank you for the reply. I installed it in a conda environment, and I found that the error occurred because transformers-cli was not installed under the main/ directory. After manually copying it there, the problem solved.
